SWI-Prolog/swipl-devel

- boot/packs.pl
A machine that runs a saved state may have a different file system
layout than the one which built the saved state.
> FIXED: Make pack locations volatile

- library/prolog_pack.pl
This makes pack_install stop with error message when pack is already installed unless `upgrade(true)` option is set. I believe this was the original intent but the code used `update` option with inverted value and cut was missing which made the pack installed despite the error message.
> Make pack_install stop with error when pack is already installed

- library/heaps.pl
Added the individual operations' time complexities.
The Pettie reference is unnecessary since we don't support decrease-key
anyway, and I wouldn't know how to ever fit that into a persistent
implementation of pairing heaps except by brute-force search.
> DOC: complexity of heaps library operations

- library/explain.pl
Because it is no longer an atom but a special constant. Discovered by Pasi Xyy
on the mailing list.
> Updated explanation for []

- library/heaps.pl
The is_pairing_heap function is not working because of wrong comparison, this will fix it.
> fixed is_heap

- man/extensions.doc
it seems there is a typo in the documentation of  string_predicate/1 (module name omitted)
> DOC: typo in string_predicate/1 usage example

- boot/topvars.pl
Saving variables with attributes to the toplevel reusable bindings.
> Fix for https://github.com/SWI-Prolog/swipl-devel/issues/101 - Saving variables with attributes to the toplevel reusable bindings.

- man/builtin.doc
The most important change: State that the content is actually included at the precise *position* of the directive. This is relevant to preserve the order of included clauses. See [Proloxy](https://github.com/triska/proloxy) for an example where this matters.
The rest is an attempt to make the documentation easier to understand, please review and merge if applicable. Thank you!
> documentation improvements for include/1

- src/configure.in
Mac OS X does not support `protected` visibility, plus it doesn't
generate `hidden` in the assembly file, but `private_extern`.
> FIXED: check visibility attribute support of compiler

- library/error.pl
In the 1st clause of is_of_type/2, nonvar(Term) is called instead of nonvar(Type).  I have fixed the variable reference.
> FIXED: Variable reference in is_of_type/2.

- man/module.doc
About importing modules without using any of their predicates.  This fixes issue #5 .
> DOC: Added paragraph on best practice for modules.

- man/overview.doc
The programmer is most likely to look for these incompatibility issues
in:
1. The section on command line options, where the `--traditional`
flag is described.
2. The section on `current_prolog_flag/2`, where flag `traditional`
indicates that taditional mode is turned on.
This fixes issue #149
> DOC: Clarified some of the repercusions of using --traditional

- man/overview.doc
See http://www.swi-prolog.org/pldoc/man?section=varprefix
> Spelling in `varprefix` documentation

- src/Makefile.in
- src/os/pl-prologflag.c
To allow [reproducible builds](https://reproducible-builds.org/) (same source results in same binary) replace
`__DATE__` and `__TIME__` with system provided values.
This is used e.g. by [debian](https://wiki.debian.org/ReproducibleBuilds), openSUSE also recommends to patch usage of `__DATE__` and `__TIME__` as leads to a lot of rebuilds even when source did not change, for more information: https://reproducible-builds.org/specs/source-date-epoch/
> ENHANCED: Allow reproducible builds by using the SOURCE_DATE_EPOCH variable

- boot/expand.pl
- library/prolog_clause.pl
Hi Jan,
I notice that some variables where not marked as non-fresh, when they first appeared in a predicate with a meta_predicate declaration, but also on the extended arguments of a meta-argument (greater than zero).
I don't have a short example, I saw such inconsistency while I was trying to use such information in a static analysis tool, but may be this will also fix the parts of the compiler that use that.
The second change in ubody/5 is simply that probably you forgot to add a clause to process parentheses_term_position/3.
Best Regards
> Non fresh variables

- man/overview.doc
Unix-users at the end of [§2.1.1.1 Starting SWI-Prolog on Unix](http://www.swi-prolog.org/pldoc/man?section=startunix) are redirected to [§2.1.3 Executing a query](http://www.swi-prolog.org/pldoc/man?section=execquery) but this skips [§2.1.1 Adding rules from the console](http://www.swi-prolog.org/pldoc/man?section=consultuser) which is equally relevant to them.
> correct redirection of Unix-users

- man/overview.doc
In particular, note that the ability to run subsets of Prolog code,
let alone arbitrary Prolog code, is not a necessary condition for
Spectre attacks. It suffices that sensitive data is speculatively
accessed, and that this data can be leaked. Also trusted code may be
vulnerable to this if it contains branches that are dependent on
untrusted data.
Decreasing the resolution of timers does _not_ reliably prevent
Spectre attacks. Full mitigation may require compiler support to
disable speculative access of sensitive data.
> DOC: Improve description of the new mitigate_spectre flag.

- library/assoc.pl
This can significantly improve efficiency in cases users use
gen_assoc/3 instead of get_assoc/3. Importantly, this also improves
determinism and retains full generality. A motivating example was
recently provided by Boris Vassilev when implementing a DFA that can
both parse and generate lists. The transition table can be modeled via
nested association lists, associating states to further associations
that map characters from the alphabet to subsequent states. With this
patch, using gen_assoc/3 for the latter ensures determinsm if possible
and still lets you generate all solutions for more general queries.
> ENHANCED: In gen_assoc/3, automatically use get_assoc/3 if Key is ground.

- man/overview.doc
> Small typo fix

- library/rbtrees.pl
This PR fixes issues is the `rbtrees` library module.
> Remove duplicated meta_predicate/1 directives and use numbers for closures

- library/optparse.pl
cf comment 2018-06-15T14:39:55 on http://www.swi-prolog.org/pldoc/man?section=optparse
> fixed bug preventing long options from containing underscore

- man/foreign.doc
This was missing from the docs.
> DOC: document PL_current_prolog_flag

- src/Tests/eclipse/string_tests.tst
- src/pl-string.c
There is a bug in the current implementation of `string_code/3`:
* `-,+,-` mode uses 0-based index, and
* `+,+,-` mode uses 1-based index as shown below:
```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.7.25)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.
For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).
1 ?- string_code(I,"ABC",C).
I = 0,                          <------------ notice the 0
C = 65 ;
I = 1,
C = 66 ;
I = 2,
C = 67.
2 ?- string_code(1,"ABC",C).    <------------ notice the 1
C = 65.
3 ?-
```
This PR:
* fixes the problem using a 1-based index for both, in accordance with the documentation. 
* adds a test
> FIXED: string_code/3 1-based index for  -,+,- and +,+,- modes

- man/overview.doc
Section "Force only underscore to introduce a variable"
> DOC: Typo in 2.16.1.7

- cmake/AndroidTargets.cmake
Fix 'fopen64' not found in termux.
> PORT: Android minizip USE_FILE32API

- library/sandbox.pl
`sandbox:verify_safe_declaration/1` leaves a choicepoint for `Module:Goal`, back-tracking to `Goal` and a permissions error after succeeding.
> FIXED: verify_safe_declaration/1 leaves a choicepoint

- cmake/Config.cmake
- src/pl-thread.c
I made a mistake:
contrary to my claim in 91f03daf6, pthread.h doesn't pull in the files
necessary to consume sys/cpuset.h, but sys/param.h does.
I'm sorry! I still don't know how could the test build on FreeBSD be successfull...
> PORT: fixes 91f03daf6, FreeBSD headers

- man/overview.doc
Section [*Character Escape Syntax*](http://www.swi-prolog.org/pldoc/man?section=charescapes)
> Correct spelling in 2.16.1.3

- library/error.pl
`html_text/[1,2]` doesn't support html like this:
```
<tr><td>row 1 column 1</td><td>row 1 column 2</td></tr>
<tr><td>row 2 column 1</td></tr>
```
This is the kind of html generated by pldoc for the first two rows of the `must_be/2` table.
This workaround keeps the table with two columns for each row, and so it works with `html_text`.
> Workaround so that must_be docs work with html_text/[1,2]

- library/edit.pl
[Neovim](https://github.com/neovim/neovim) is a popular modern alternative (refactoring of the original Vim codebase) to Vim, which aims to provide more modern experience of development.
> Add neovim support for edit_command/2

- cmake/AndroidTargets.cmake
- src/minizip/ioapi.h
Hopeful Fix for  #507; System resources not found error. This error occurs only on some very specific android systems. So far only on android 7.1.1, armv7l, 32bit.
> PORT: Android minizip to use consistent file api

- boot/messages.pl
I fixed the config_files url to point to the www version.
This might not be the fix needed by the malware issue, 
but it's something that needs to be fixed anyway..
I also changed the other links to point to the https versions, since the url is redirected anyway and for consistency with the new one.
I tried to build the windows version locally, but I can't get the wine build to work...
> Fix url in messages.pl

- packages/cmake/PackageDoc.cmake
This was done for man/CMakeLists.txt on 8 October 2019, but the  "-f none" is not present in packages/cmake/PackageDoc.cmake (and caught me yesterday).
Note that there is still one invocation of PROG_SWIPL in cmake/QLF.cmake, which I have not changed since I am confident I don't know whether it needs changing.
This pull request is also an experiment to see if I can follow the instructions for submitting patches in usable form.
> Add '-f none' to invocations of PROG_SWIPL, to avoid interference from init.pl

- snap/local/snap.md
Show where the config files are relocated in a snap.
Add the instructions to enable unconnected interfaces
> Update snap.md with config files and interfaces

- man/chr.doc
- man/foreign.doc
- man/overview.doc
- man/runtime.doc
- src/pl-init.c
- src/swipl.1.in
Commits with formatting changes:
* Sort prolog flags
* Use hyphen as word-separator for long options
Commits with fixes:
* Remove invalid short options
* Fix missing hyphens in command line options
* Fix typos in manual
~~p/s: please fix the typo in one of the commit message, just noticed it when creating this PR. :flushed:~~
*EDIT:*
Fixed the typo in the commit message using git interactive rebase and force push.
I think it's safe to force push if nobody depends on my branch.
> Changes and fixes related to flags and options

- man/builtin.doc
- man/ide.doc
In `man/builtin.doc`, line 5095 refers to a nonexistent predicate `tcp_sockopt/2`.
> DOC: Fix typos in manual

- man/builtin.doc
- man/extensions.doc
- man/foreign.doc
- man/lib/nbset.doc
- man/module.doc
- man/overview.doc
- man/tabling.doc
- man/threads.doc
- man/windows.doc
Off-Topic:
`man/windows.doc` is not in the build file.
As a result, the `windows.html` in `plweb-www` is out-of-sync from the current `man/windows.doc`.
However, it's still being referred to in the [download page](https://www.swi-prolog.org/download/stable).
> DOC: Fix and changes in manual

- man/pl.bib
BibTeX complains that booktitle is missing from this entry.  The real problem is that it should have type \@article, not \@inproceedings, and the volume and number are missing.
> Fix DBLP:dblpjournals/tplp/CovingtonBOWP12 BibTeX entry.

- man/builtin.doc
I have reviewed the manual chapter "4.10.3 The exception term" once more because the text didn't make me all that happy, it didn't "flow" well. Also removed the commented-out exception details, no need to keep those around (they are in the repo after all).
> DOC: Reviewed "4.10.3 The exception term"

- man/summary.doc
- man/threads.doc
In `man/threads.doc`, there were 2 predicate name typos which I'm not confident of my fixes:
* Line 142, `setlocale/1` -> `set_locale/1` (might be `setlocale/3`?)
* Line 684, `thread/2` -> `thread_wait/2`
> Fix typos and format summary.doc

- customize/init.pl
- man/overview.doc
After reading carefully through the discussions of rational numbers [here](https://swi-prolog.discourse.group/t/proper-rational-numbers-prototype-for-testing-discussion/3161/75), [here](https://swi-prolog.discourse.group/t/ann-swi-prolog-8-1-22/1867?u=fnogatz) and [here](https://github.com/SWI-Prolog/swipl-devel/issues/539), I came to the conclusion that the consensus about the syntax for rational numbers in SWI-Prolog is `1r3` instead of the formerly discussed `1R3`. At least, the latter always throws a syntax error ;)
I therefore suggest to correct the documentation accordingly :grinning: I checked via `grep -R '[1-9]R[1-9]'`, these seem to be the only occurrences of the legacy syntax with the uppercase `R`.
> DOC: Correct examples for rational numbers

- library/qsave.pl
Fixes "Format error: too many arguments" when `qsave_program/2` uses `map/1` option
> FIXED:  Using `map/1` option in `qsave_program/2` no longer causes "Format error: too many arguments"

- man/builtin.doc
Slight touches to the documentation. In particular:
- The PDF at the "Delimited Continuations" page somehow pointed to a draft for C++ standardization. Made it point to the correct preprint PDF on the SWI-Prolog server.
- is_list/2 had a slight off description, using "functor" (name/arity) instead of "functor name" or "compound term name"
- predsort/3 was unclear about deletion of duplicates. Made clearer.
- Otherwise typo fixes
> DOC: Slight touches to the documentation.

- library/dialect/sicstus.pl
- library/dialect/sicstus/block.pl
Mostly fixes #731.
I've also added declarations for a few missing SICStus built-in operators. `mode` is probably the most useful one here. `spy` and `nospy` probably aren't used much in actual code, but it can't hurt to have them declared. The `do` declaration isn't all that useful, because the actual functionality of `do` loops isn't implemented, but this way they can at least be parsed.
> Operator-related fixes to SICStus emulation

- library/apply.pl
As it was before, it wasn't obvious from reading the docs that partial application is allowed.
> DOC: document use of call/N explicitly

- library/dialect/sicstus.pl
- library/dialect/sicstus/arrays.pl
- library/dialect/sicstus/block.pl
- library/dialect/sicstus/lists.pl
- library/dialect/sicstus/sockets.pl
- library/dialect/sicstus/system.pl
- library/dialect/sicstus/terms.pl
- library/dialect/sicstus/timeout.pl
- library/dialect/sicstus4.pl
- library/dialect/sicstus4/lists.pl
- library/dialect/sicstus4/system.pl
- library/dialect/sicstus4/terms.pl
- library/dialect/sicstus4/timeout.pl
- src/CMakeLists.txt
As discussed [on Discourse](https://swi-prolog.discourse.group/t/expects-dialect-sicstus-how-to-handle-sicstus-3-vs-4-api-conflicts/3381), it's not possible to properly emulate SICStus 3 and 4 as a single dialect, because of some API changes that would lead to name conflicts. This PR adds a separate `sicstus4` dialect that emulates just SICStus 4, and moves the few SICStus 4-only features from the `sicstus` dialect to `sicstus4`.
The SICStus 4 emulation reuses/re-exports many parts of the SICStus 3 emulation. I've made small changes to the term/goal expansions in library/dialect/sicstus.pl so that they take effect in both SICStus 3 and 4 mode. It's not very nice that the `sicstus` (3) dialect now has code in it that's only used by the `sicstus4` dialect, but this way the term/goal …
> Add initial SICStus 4 emulation (split from existing SICStus 3 emulation)

- library/dialect/sicstus4/sockets.pl
- src/CMakeLists.txt
Implements everything except the server socket-related predicates (which I'll probably do later) and some minor options/features (which I didn't need).
> SICStus 4 library(sockets) emulation

- library/dialect/sicstus.pl
- library/dialect/sicstus4.pl
Most of these keys could probably be implemented natively in SWI instead, as "compatibility keys" like the current set of Quintus/SICStus-compatible keys. Some of the keys defined here conflict with their normal SWI meaning though (specifically `garbage_collection` and `atoms`) and would need to stay in the SICStus emulation. Also, SWI's current implementation of statistics/2 seems to assume that all "compatibility keys" return a list value, which is no longer true as of SICStus 4.1, which adds many single integer statistics.
I currently implemented this by defining a custom statistics/2 predicate in library(dialect/sicstus) and library(dialect/sicstus4). This seems to work without issues (except for #771), but based on [this Discourse …
> Add more statistics/2 keys to SICStus emulation, mostly from SICStus 4

- library/clp/clpfd.pl
This should fix #568. I've also added `div` propagation so that the bitshift propagation code is a bit simpler, and to make it more precise.
What's remaining is to edit the docs to note that the bitshifts are being propagated, and I also want to check my arithmetic again.
> Implement propagation of clp(fd) bitshifts and `div`

- README.md
Minor changes for `README.md`:
- Correct grammar
- Update link to latest Pro Git book version
- Use https for links to swi-prolog.org
> Update README.md: Grammar and Links

- man/engines.doc
Just fixed a word (maybe it should have been "penned"?)
"The idea was pinned by Paul Tarau Tarau, 2011." to
"The idea was developed by Paul Tarau Tarau, 2011."
> DOC: "pinned" -> "developed"

- library/dialect/sicstus4.pl
- library/dialect/sicstus4/types.pl
- src/CMakeLists.txt
SICStus copy_term/2 behaves like SWI copy_term_nat/2, i. e. it doesn't copy attributes. That one was fun to debug...
> Add library(types) and copy_term/2 to SICStus 4 emulation

- src/Tests/core/test_format.pl
- src/os/pl-fmt.c
Without this, I see silent success, tested on 8.3.24-31-g79ac16a36:
```
?- format('~`*t~*|', [-1]).
true.
?- format('~`*t~*+', [-1]).
********
true.
```
> FIXED: negative numerical argument for format from argument list

- library/clp/clpfd.pl
Previously, expressions like this silently failed for no reason:
```prolog
?- A #= B div 3.
false.
```
I'm not a CLP(FD) expert, but this seems to be a simple typo in the code. With that fixed, it works as expected:
```prolog
?- A #= B div 3.
B div 3#=A.
?- A #= B div 3, A #= 5.
A = 5,
B in 15..17.
?- A #= B div 3, B #= 5.
A = 1,
B = 5.
```
> Fix silent failure in CLP(FD) domain calculation for truncated division

- src/CMakeLists.txt
- src/pl-alloc-inline.h
- src/pl-alloc.c
- src/pl-alloc.h
- src/pl-fli-inline.h
- src/pl-fli.c
- src/pl-funcs.h
- src/pl-incl.h
- src/pl-wam.c
**[NOTE: this is an alternative to PR #843. If the performance issues in that one can't be resolved but this one works, this is a perfectly acceptable alternative.]**
This adds USE_*_INLINES as a flag that can be set before including
pl-incl.h, to include some of the function definitions from various
files in a "can-inline" context. It also separates the majority of
pl-alloc.c, pl-index.c, and pl-fli.c out into their own object files,
to speed up the build.
This may result in a slight (1-2% at max, in my testing) performance
loss since the pl-wam compilation doesn't have access to *all* the
function definitions in those three files, but enabling LTO on the
build (which I have not yet, since it currently generates warnings)
avoids the performance drop entirely by allowing the linker itself …
> BUILD: Moved pl-alloc/index/fli out of pl-wam

- library/dialect/sicstus4/samsort.pl
Nothing complex, just a renaming. No idea why I forgot this one.
> ADDED: samkeysort/2 to SICStus 4 library(samsort) emulation.

- library/dialect/sicstus4/file_systems.pl
- src/CMakeLists.txt
This should be pretty complete. The only missing predicate is `close_all_streams/0` - I have no idea what practical uses that has...
Many file/directory properties aren't implemented, because SWI doesn't have any equivalent APIs. But all of the important ones are supported (size, modified timestamp, access permission).
> Add library(file_systems) to SICStus 4 emulation

- library/dialect/sicstus4/clpfd.pl
- src/CMakeLists.txt
This is obviously nowhere close to a full emulation of the SICStus CLP(FD) API. These are just a few simple predicates/operators that SWI's CLP(FD) already supports under different names.
> Add partial library(clpfd) to SICStus 4 emulation

- library/dialect/sicstus.pl
- library/dialect/sicstus4.pl
Uses the new `trim_heap/0` in the emulated `trimcore/0`, and fixes some problems with emulating Quintus/SICStus-specific Prolog flags.
> A few more misc SICStus emulation updates

- src/pl-trace.c
In the recent refactor of the trace help display, the name of the `w` command was accidentally changed to `s`, and the `p` command was dropped completely.
> Fix help messages for trace commands p and w

- library/clp/clpfd.pl
Some CLP(FD) multiplications leave a lot of strange residual variables and constraints, which stay around even after all of the user-provided variables have been bound and a complete solution has been found. This is only visible when using `call_residue_vars/2`:
<details>
<summary>Example (long output)</summary>
```prolog
?- 10 #= Y * Z.
Y in -10.. -1\/1..10,
Y*Z#=10,
Z in -10.. -1\/1..10.
?- call_residue_vars((10 #= Y * Z), Vars).
Vars = [_37334, _37340, _37346, _37352, _37358, _37364, _37370, _37376, _37382, _37388, _37394, _37400, _37406, _37412, _37418, _37424, _37430, _37436, _37442, _37448, _37454, _37460, _37466, _37472|...],
Y in -10.. -1\/1..10,
Y*Z#=10,
Z in -10.. -1\/1..10,
_37334 in 1..10,
_37340*_37334#=10,
_37340 in 1..10,
_37346 in -10.. -1,
_37352*_37346#=10,
_37352 in …
```
> Fix CLP(FD) multiplication leaving a lot of residual variables

- src/pl-trace.c
Listing, in particular, suffers from not having the newline printed after the command name, since the first line ends up being smashed against the right margin.
> FIXED: Adding missing newlines in tracer commands

- boot/messages.pl
Fixes message printing of the duplicate pack warning (format/3 contains too many arguments)
> Fixes the printing of duplicate package warning

- man/hack.doc
Add a documentation item about using prolog_choice_attribute/3 with argument `Key = pc`.
> DOC: Document key `pc` of prolog_choice_attribute/3

- src/os/pl-cstack.c
The pclose() call, in addition to calling fclose(), also calls wait() to avoid creating zombie processes.
> Pair pclose, not fclose, with popen

- library/dialect/sicstus/system.pl
SICStus 3 only had the mode datime(+When, -Datime), but SICStus 4 also supports datime(-When, +Datime), for building timestamps from datime records.
> Implement SICStus datime/2 mode datime(-When, +Datime)

- src/os/pl-prologflag.c
solves a warning under MSYS2/Rtools42 compilation
> _timezone under __WINDOWS__ or __CYGWIN__

- man/hack.doc
The documentation implies that when a breakpoint triggers the tracer, `prolog_trace_interception/4` will be called with a `break(PC)` term as the `Port` argument, but this appears not to be the case since commit 8ffb94a2c49f4146ec9fcdaa85818730323dbbe8.
> DOC: Remove obsolete reference of `break/1` trace port

- library/prolog_pack.pl
Fixing the [accept also the archive/refs/tags](https://github.com/SWI-Prolog/swipl-devel/issues/935#issuecomment-1044338213)
> github url with archive/refs/tags is now also accepted

- src/CMakeLists.txt
- src/pl-builtin.h
- src/pl-setup.c
This allows for a standards-compatible implementation of the LD macros
that is guaranteed to compile down to a simple reference even at -O0.
I've also added some code that, at least in my testing, makes
`print LD` work again in GDB and any debugger that uses it as a backend.
> MODIFIED: switching core libswipl code to C11

- src/pl-fli.c
- src/pl-global.h
- src/pl-incl.h
- src/pl-inline.h
- src/pl-setup.c
- src/pl-thread.c
- src/pl-wam.c
This also introduces a set of macros to interact with the pending signal
mask which should hopefully ease refactoring if and when we change which
signals swipl supports, like adding support for system signals over 31.
> MODIFIED: fixing SIG_PROLOG_OFFSET at 32, per docs

- man/builtin.doc
- src/SWI-Prolog.h
- src/pl-setup.c
This allows for requesting the SIG_IGN disposition, and also unifies the
SIGPIPE behavior with the other initially-prepared signals. Technically,
this could be considered a backwards-incompatible change. However, for
this to actually affect someone's working code, they would have to
1. Redefine the system predicate ignore/1,
2. Call `on_signal(Sig, _, ignore)`, AND
3. Expect `ignore(Signal)` to do something besides ignoring Signal;
and in that case I think we can all agree they've brought this trouble
upon themselves. :)
Also adds SIGPIPE's default disposition to the docs.
> ADDED: on_signal/3 now takes value 'ignore'

- src/config/wincfg.h
Avoids a warning on a refefinition of MAXPATHLEN in MinGW/RTools42 
/ucrt64/include/sys/param.h:41: warning: "MAXPATHLEN" redefined
In sys/param.h MAXPATHLEN actually refers to PATH_MAX defined in /crt64/include/limits.h where it is 260 not 512.
> Set MAXPATHLEN to PATH_MAX

- library/dif.pl
- src/Tests/attvar/test_dif.pl
Before:
```prolog
?- dif(A, B), X = A, Y = B, X = Y.
false. % correct
?- freeze(X,true), freeze(Y,true), dif(A, B), X = A, Y = B, X = Y.
X = Y, Y = A, A = B,
freeze(B, true),
freeze(B, true). % no longer fails - bad
?- call_residue_vars((freeze(X,true), freeze(Y,true), dif(A, B), X = A, Y = B, X = Y), Vars).
X = Y, Y = A, A = B,
Vars = [_, B],
freeze(B, true),
freeze(B, true),
dif(B, B). % wat
```
After:
```prolog
?- dif(A, B), X = A, Y = B, X = Y.
false.
?- freeze(X,true), freeze(Y,true), dif(A, B), X = A, Y = B, X = Y.
false.
?- call_residue_vars((freeze(X,true), freeze(Y,true), dif(A, B), X = A, Y = B, X = Y), Vars).
false.
% all correct
```
> FIXED: dif/2 not firing after unifying with other attributed variables.

- src/Tests/core/test_answer.pl
unsure if it is that simple, but it makes the "answer" tests execute and pass on my linux and skips them on my mingw
> FIX: conditions for test_answer

- man/foreign.doc
I've also added a few sentences, which need to be verified.
> Fix typos in foreign language API docs

- boot/build_home.pl
This minor change allows for a GNU-style directory structure also under Windows. Mostly needed for the generation of SSL certificates at the end of the normal build process under MSYS2.
> PORT: add_package_path/1 also under Windows

- boot/autoload.pl
Currently setting `autoload` to `user_or_explicit` is actually equivalent to `false`:
```
1 ?- set_prolog_flag(autoload, user_or_explicit).
% Disabled autoloading (loaded 17 files)
true.
2 ?- member(X,[1,2,3]).
Correct to: "lists:member(X,[1,2,3])"? no
ERROR: Unknown procedure: member/2
```
This is because autoload is looking for `explicit_or_user`, instead of `user_or_explicit`.
> FIXED: user_or_explicit autoload mode not working

- src/pl-thread.c
I think rc can safely be initialized to FALSE
> PORT: Suppress uninit warning in msys2

- src/os/pl-file.c
Fixes #1025 , array bounds check was wrong.
Tested with:
```prolog
?- with_output_to(string(S), stream_property(current_output, encoding(E))).
S = "",
E = wchar_t.
```
> FIXED: Issue#1025: stream encoding wchar_t not returned as stream property

- src/wasm/prolog.js
This PR avoids error when running WebAssembly version in Node as there is no `window` object available.
> Avoiding ReferenceError while running WebAssembly version in Nodejs

- packages/cmake/PrologPackage.cmake
Otherwise on macOS, if libswipl.dylib is in a non-standard location, shared modules (e.g. sweep-module) will be unable to find it
As discussed [on the forum](https://swi-prolog.discourse.group/t/sweep-swi-prolog-embedded-in-emacs/5713/46).
> Set @rpath correctly for modules when installing to prefix

- src/libbf/bf_gmp.c
Add initial reduction using Euclidean algorithm (remainder) if a and b sufficiently different. This has little effect if n1 and n2 are in the same range (e.g., `bench(gcd,1000,200,200)` but can make a big difference if there's a large spread (e.g., `bench(gcd,1000,100,300)`). I.e., this somewhat addresses worst case scenarios but still falls way short of GMP.
> Additional performance tweaks to mpz_gcd

- src/libbf/bf_gmp.c
- src/libbf/bf_gmp.h
Fixed a couple of bugs, improved compatibility with GMP rationals, and added a few GMP functions for possible use in correctely rounded comparison. (Note: mpz_set_si addition for compare functionality, not mpz_rootrem fix as stated in commit doc.)
> bf_gmp fixes and additions

- cmake/GCCBuiltins.cmake
Future compilers may not support implicit ints or implicit function declarations, so avoid them, by using an explicit int type and including <alloca.h> for the alloca function.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> cmake: Fix C99 compatibility issues in GCC built-in detection

- src/os/SWI-Stream.h
I will fix warnings from the format checker in other PRs (this is a low-priority activity, as most (but not all!) of the warnings are for debug print statements).
> Added printf format checking to some printf-like functions

- src/wasm/prolog.js
Otherwise this causes errors in `node`
```
1) SWI-Prolog WebAssembly on Node.js
[node] should conform to certain typing:
ReferenceError: HTMLCollection is not defined
at /home/jesse/Documents/github/npm-swipl-wasm/dist/swipl/swipl.js:9:184617
at module.exports (dist/swipl-node.js:8:10)
at Context.<anonymous> (tests/node.js:14:27)
at process.processImmediate (node:internal/timers:471:21)
```
> fix: Use `globalThis` to reference html collections

- src/wasm/pre.js
Resolves the issue observed in https://github.com/SWI-Prolog/swipl-devel/pull/1088#issuecomment-1399651681
> handle `preRun` as a function rather than an array

- man/wasm.doc
This PR is a small suggestion for adjusting the introduction section of the WASM port manual to put less focus on the implementation and more on the potential usage (running SWI-Prolog in the browser).
> DOC: tweak WASM port introductory text

- library/main.pl
It seems from reading the source (and indeed, what one would expect), that the argument is considered a boolean if the next argument *does* start with a hyphen.
> Correct documentation for disjunctive opt_type

- man/foreign.doc
- src/SWI-Prolog.h
These items have been documented as deprecated; the DEPRECATED flags are currently commented out because they are still used in the source.
> Add deprecations to SWI-Prolog.h

- src/wasm/prolog.js
See https://github.com/emscripten-core/emscripten/blob/b1fbec18442635058b362d36bc613ed9cecd5f17/ChangeLog.md?plain=1#L61.
I have tested this on 3.1.37 of emscripten. It does fix the build error encountered in https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/4843424186/jobs/8631031803?pr=127 but we are also getting a `_free` is undefined error which we may wish to also resolve before merging this change.
> chore: use `stringToNewUTF8` instead of `allocateUTF8`

- library/www_browser.pl
www_open_url leaves a choice point that is useless in Windows
> for windows, open_url/1 cut

- library/prolog_deps.pl
This fixes an error in `file_autoload_directives/3` introduced in 8019b12f47130799caa611791b5f5bf4fc51ba51
> FIXED: prolog_deps:src_file/2 SSU error

- src/pl-segstack.c
below, we have ptr + number, which raises a warning on pointer arithmetic if ptr is void*. Since stack->top is char* anyway, this seems harmless (though uint8_t could be used instead of char)
> Minor fix in pl-segstack.c

- src/mkvmi.c
The error is raised because we have e5 -= 0 for e5 == NULL
else-branch of if ( !e4 || (is_vmh && !e5) )
<=> e4 && !(is_vmh && !e5)
<=> e4 && (!is_vmh || e5)
Consequence is e4-- (which is fine) and e5 -= is_vmh which is either a noop* for is_vmh == 0 or fine for is_vmh != 0 && e5 != NULL.
*The noop case raises the error if e5 == NULL.
> CLEANUP: avoid UBSAN error in mkvmi.c

- src/pl-qlf.c
UBSAN complained about a left shift of -1
> CLEANUP: workaround for an UBSAN error

- library/prolog_pack.pl
Per #1305, currently trying to install a pack from a local dir will fail if git is not present, even if git would not be required to run the install.
This PR modifies the behavior of `pack_unpack_from_local/5` to check the options for an explicitly set `git(false)`, in which case the check for a git directory is skipped.
> prolog_pack: only check for git dir if git(false) is not in options

- man/builtin.doc
- man/foreign.doc
Some  changes i'm making to packages/cpp depend on the precise behavior of absolute_file_name and PL_get_file_name().
> Minor clarifications to documentation of absolute_file_name and PL_get_file_name()

- CMAKE.md
This tiny change ensures the table is nicely aligned regardless of tab display width.
> Whitespace-only cleanup in CMAKE.md

- src/pl-thread.c
Unsure if you like this PR, but it suppresses a warning under MSYS2 (namely, that grace_time is unused)
> Suppress unused warning under MSYS2

- library/qsave.pl
win_process_modules returns UNC paths on some systems. This patch handles dlls with UNC paths correctly.
https://swi-prolog.discourse.group/t/ann-swi-prolog-9-3-30/9258/11
> handle UNC files in prolog_dll
